/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event. Â© 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
	//"strings"
)

func ScsAsIdSubscriptionsSubscriptionIdDelete(w http.ResponseWriter, r *http.Request) {
	// urlPart := strings.Split(r.URL.Path, "/")
	// id:=urlPart[len(urlPart)-3]
	// subscriptionId:=urlPart[len(urlPart)-1]

	// for index, monitoringeventid := range monitoringevent {
	// 	if monitoringeventid.MtcProviderId == id && monitoringevent.subscriptionId == subscriptionId{
	// 		monitoringevent = append(monitoringevent[:index], monitoringevent[index+1:]...)
	// 		w.WriteHeader(http.StatusOK)
	// 		w.Write([]byte(`{"message": "Success to delete "}`))

	// 	}
	// }
	// json.NewEncoder(w).Encode(getmonitoringevent)
	// //w.WriteHeader(http.StatusOK)

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
