/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event. Â© 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PdnConnectionInformation struct {
	Status *PdnConnectionStatus `json:"status"`
	// Identify the APN, it is depending on the SCEF local configuration whether or not this attribute is sent to the SCS/AS.
	Apn string `json:"apn,omitempty"`
	PdnType *PdnType `json:"pdnType"`
	InterfaceInd *InterfaceIndication `json:"interfaceInd,omitempty"`
	Ipv4Addr string `json:"ipv4Addr,omitempty"`
	Ipv6Addrs []string `json:"ipv6Addrs,omitempty"`
}
