/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event. Â© 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MonitoringEventSubscription struct {
	Self              string `json:"self,omitempty"`
	SupportedFeatures string `json:"supportedFeatures,omitempty"`
	// Identifies the MTC Service Provider and/or MTC Application.
	MtcProviderId           string   `json:"mtcProviderId,omitempty"`
	ExternalId              string   `json:"externalId,omitempty"`
	Msisdn                  string   `json:"msisdn,omitempty"`
	ExternalGroupId         string   `json:"externalGroupId,omitempty"`
	AddExtGroupId           []string `json:"addExtGroupId,omitempty"`
	Ipv4Addr                string   `json:"ipv4Addr,omitempty"`
	Ipv6Addr                *string  `json:"ipv6Addr,omitempty"`
	NotificationDestination string   `json:"notificationDestination"`
	// Set to true by the SCS/AS to request the SCEF to send a test notification as defined in subclauseÂ 5.2.5.3. Set to false or omitted otherwise.
	RequestTestNotification bool            `json:"requestTestNotification,omitempty"`
	WebsockNotifConfig      string          `json:"websockNotifConfig,omitempty"`
	MonitoringType          *MonitoringType `json:"monitoringType"`
	// Identifies the maximum number of event reports to be generated by the HSS, MME/SGSN as specified in subclauseÂ 5.6.0 of 3GPPÂ TSÂ 23.682Â [2].
	MaximumNumberOfReports int32             `json:"maximumNumberOfReports,omitempty"`
	MonitorExpireTime      string            `json:"monitorExpireTime,omitempty"`
	RepPeriod              string            `json:"repPeriod,omitempty"`
	GroupReportGuardTime   string            `json:"groupReportGuardTime,omitempty"`
	MaximumDetectionTime   string            `json:"maximumDetectionTime,omitempty"`
	ReachabilityType       *ReachabilityType `json:"reachabilityType,omitempty"`
	MaximumLatency         string            `json:"maximumLatency,omitempty"`
	MaximumResponseTime    string            `json:"maximumResponseTime,omitempty"`
	// If \"monitoringType\" is \"UE_REACHABILITY\", this parameter may be included to identify the number of packets that the serving gateway shall buffer in case that the UE is not reachable.
	SuggestedNumberOfDlPackets int32 `json:"suggestedNumberOfDlPackets,omitempty"`
	// If \"monitoringType\" is set to \"UE_REACHABILITY\" or \"AVAILABILITY_AFTER_DDN_FAILURE\", this parameter may be included to indicate the notification of when a UE, for which PSM is enabled, transitions into idle mode. - \"true\"  indicate enabling of notification - \"false\"  indicate no need to notify Default  \"false\".
	IdleStatusIndication  bool         `json:"idleStatusIndication,omitempty"`
	LocationType          LocationType `json:"locationType,omitempty"`
	Accuracy              Accuracy     `json:"accuracy,omitempty"`
	MinimumReportInterval string       `json:"minimumReportInterval,omitempty"`
	MaxRptExpireIntvl     string       `json:"maxRptExpireIntvl,omitempty"`
	SamplingInterval      string       `json:"samplingInterval,omitempty"`
	// Indicates whether to request the location estimate for event reporting.
	ReportingLocEstInd bool             `json:"reportingLocEstInd,omitempty"`
	LinearDistance     string           `json:"linearDistance,omitempty"`
	LocQoS             string           `json:"locQoS,omitempty"`
	SvcId              string           `json:"svcId,omitempty"`
	LdrType            string           `json:"ldrType,omitempty"`
	VelocityRequested  string           `json:"velocityRequested,omitempty"`
	MaxAgeOfLocEst     string           `json:"maxAgeOfLocEst,omitempty"`
	LocTimeWindow      string           `json:"locTimeWindow,omitempty"`
	AssociationType    *AssociationType `json:"associationType,omitempty"`
	// If \"monitoringType\" is \"ROAMING_STATUS\", this parameter may be included to indicate the notification of UE's Serving PLMN ID. - \"true\"  The value shall be used to indicate enabling of notification; - \"false\"  The value shall be used to indicate disabling of notification.  Default  \"false\".
	PlmnIndication        bool                  `json:"plmnIndication,omitempty"`
	LocationArea          string                `json:"locationArea,omitempty"`
	LocationArea5G        string                `json:"locationArea5G,omitempty"`
	DddTraDescriptors     []string              `json:"dddTraDescriptors,omitempty"`
	DddStati              []string              `json:"dddStati,omitempty"`
	ApiNames              []string              `json:"apiNames,omitempty"`
	MonitoringEventReport MonitoringEventReport `json:"monitoringEventReport,omitempty"`
}
