/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event. Â© 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FailureCause struct {
	// Identifies a non-transparent copy of the BSSGP cause code. Refer to 3GPPÂ TSÂ 29.128Â [12].
	BssgpCause int32 `json:"bssgpCause,omitempty"`
	// Identify the type of the S1AP-Cause. Refer to 3GPPÂ TSÂ 29.128Â [12].
	CauseType int32 `json:"causeType,omitempty"`
	// Identifies a non-transparent copy of the GMM cause code. Refer to 3GPPÂ TSÂ 29.128Â [12].
	GmmCause int32 `json:"gmmCause,omitempty"`
	// Identifies a non-transparent copy of the RANAP cause code. Refer to 3GPPÂ TSÂ 29.128Â [12].
	RanapCause int32 `json:"ranapCause,omitempty"`
	// Indicates RAN and/or NAS release cause code information, TWAN release cause code information or untrusted WLAN release cause code information. Refer to 3GPPÂ TSÂ 29.214Â [10].
	RanNasCause string `json:"ranNasCause,omitempty"`
	// Identifies a non-transparent copy of the S1AP cause code. Refer to 3GPPÂ TSÂ 29.128Â [12].
	S1ApCause int32 `json:"s1ApCause,omitempty"`
	// Identifies a non-transparent copy of the SM cause code. Refer to 3GPPÂ TSÂ 29.128Â [12].
	SmCause int32 `json:"smCause,omitempty"`
}
