/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event. Â© 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LocationInfo struct {
	AgeOfLocationInfo int32 `json:"ageOfLocationInfo,omitempty"`
	// Indicates the Cell Global Identification of the user which identifies the cell the UE is registered.
	CellId string `json:"cellId,omitempty"`
	// Indicates the eNodeB in which the UE is currently located.
	EnodeBId string `json:"enodeBId,omitempty"`
	// Identifies the Routing Area Identity of the user where the UE is located.
	RoutingAreaId string `json:"routingAreaId,omitempty"`
	// Identifies the Tracking Area Identity of the user where the UE is located.
	TrackingAreaId string `json:"trackingAreaId,omitempty"`
	// Identifies the PLMN Identity of the user where the UE is located.
	PlmnId string `json:"plmnId,omitempty"`
	// Identifies the TWAN Identity of the user where the UE is located.
	TwanId         string  `json:"twanId,omitempty"`
	GeographicArea *string `json:"geographicArea,omitempty"`
	PositionMethod string  `json:"positionMethod,omitempty"`
	QosFulfilInd   string  `json:"qosFulfilInd,omitempty"`
	UeVelocity     string  `json:"ueVelocity,omitempty"`
	LdrType        string  `json:"ldrType,omitempty"`
}
