/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event. Â© 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IdleStatusInfo struct {
	ActiveTime string `json:"activeTime,omitempty"`
	EdrxCycleLength float32 `json:"edrxCycleLength,omitempty"`
	// Identifies the number of packets shall be buffered in the serving gateway. It shall be present if the idle status indication is requested by the SCS/AS with \"idleStatusIndication\" in the \"monitoringEventSubscription\" sets to \"true\".
	SuggestedNumberOfDlPackets int32 `json:"suggestedNumberOfDlPackets,omitempty"`
	IdleStatusTimestamp string `json:"idleStatusTimestamp,omitempty"`
	PeriodicAUTimer string `json:"periodicAUTimer,omitempty"`
}
