/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event. Â© 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MonitoringEventReport struct {
	ImeiChange     *AssociationType `json:"imeiChange,omitempty"`
	ExternalId     string           `json:"externalId,omitempty"`
	IdleStatusInfo *IdleStatusInfo  `json:"idleStatusInfo,omitempty"`
	LocationInfo   LocationInfo     `json:"locationInfo,omitempty"`
	// If \"monitoringType\" is \"LOSS_OF_CONNECTIVITY\", this parameter shall be included if available to identify the reason why loss of connectivity is reported. Refer to 3GPPÂ TSÂ 29.336Â [11] SubclauseÂ 8.4.58.
	LossOfConnectReason   int32                `json:"lossOfConnectReason,omitempty"`
	MaxUEAvailabilityTime string               `json:"maxUEAvailabilityTime,omitempty"`
	Msisdn                string               `json:"msisdn,omitempty"`
	MonitoringType        *MonitoringType      `json:"monitoringType"`
	UePerLocationReport   *UePerLocationReport `json:"uePerLocationReport,omitempty"`
	PlmnId                string               `json:"plmnId,omitempty"`
	ReachabilityType      *ReachabilityType    `json:"reachabilityType,omitempty"`
	// If \"monitoringType\" is \"ROAMING_STATUS\", this parameter shall be set to \"true\" if the UE is on roaming status. Set to false or omitted otherwise.
	RoamingStatus     bool                      `json:"roamingStatus,omitempty"`
	FailureCause      *FailureCause             `json:"failureCause,omitempty"`
	EventTime         string                    `json:"eventTime,omitempty"`
	PdnConnInfo       *PdnConnectionInformation `json:"pdnConnInfo,omitempty"`
	DddStatus         string                    `json:"dddStatus,omitempty"`
	DddTrafDescriptor string                    `json:"dddTrafDescriptor,omitempty"`
	MaxWaitTime       string                    `json:"maxWaitTime,omitempty"`
	ApiCaps           []ApiCapabilityInfo       `json:"apiCaps,omitempty"`
}
